version: "3.9"

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    # directorios para el archivo de configuración y archivos del static
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./app/static:/var/www/static 
    depends_on:
      - web
